import "oaidl.idl";
import "ocidl.idl";
import "strmif.idl";

interface IOSPGraphEventHandler;
interface IOSPServiceMgr;

[
	object,
	uuid(F18EEA95-A736-4aad-B8EB-25472C28036C)
]
interface IOSPGraph : IUnknown
{
	HRESULT Init(IOSPGraphEventHandler* aEventHandler, IOSPServiceMgr* aServiceMre);
	HRESULT Render(BSTR aUrl);
	HRESULT get_Url(BSTR* ppUrl);
	HRESULT Play();
	HRESULT Pause();
	HRESULT Stop();
	HRESULT GetCurrentPos(long* aPos);
	HRESULT GetDuration(long* aPos);
}

[
	object,
	uuid(DB5AAF0B-9810-47a0-A16C-BA60C5D6CD54)
]
interface IOSPGraphEventHandler : IDispatch
{
	HRESULT NotifyEvent([in]ULONG_PTR punkGraph, [in]long aEventCode, [in]LONG_PTR wEventParam, [in]LONG_PTR lEventParam);
	HRESULT NotifyError([in]ULONG_PTR punkGraph, [in]long aErrCode, [in]long param);
	HRESULT NotifyGraphStateChange([in]ULONG_PTR punkGraph, [in]long aState);
	HRESULT NotifyStreamEnd([in]LONG_PTR punkGraph);
	HRESULT NotifyVolumnChange([in]LONG_PTR punkGraph, [in]long aVolumn, [in]BOOL aMute);
}

[
	object,
	uuid(20F3BC30-AD68-41ce-A173-B3420CE3DFCC)
]
interface IOSPGraphBuilderCallback : IUnknown
{

}

[
	object,
	uuid(E15D0A7D-0E6F-4ce8-9245-512F6A0FBDF4)
]
interface IOSPGraphBuilder : IUnknown
{
	HRESULT RenderFile(IGraphBuilder* pGb, LPCWSTR aFile, IOSPGraphBuilderCallback* aCalback);
}

[
	object,
	uuid(C8AC3067-97D2-4654-B61F-9B88B075B509)
]
interface IOSPServiceMgr : IUnknown
{
	HRESULT RenderUrl(IGraphBuilder* pGb, LPCWSTR aFile, IOSPGraphBuilderCallback* aCallback);
	HRESULT RenderFilter(IGraphBuilder* pGb, IBaseFilter* aFilter, IOSPGraphBuilderCallback* aCallback);
	HRESULT RenderPin(IGraphBuilder* pGb, IPin* aPintout, IOSPGraphBuilderCallback* aCallback);
}