#define _FACOSP		0x30A

#define MAKE_OSP_HRESULT(c)		MAKE_HRESULT(1, _FACOSP, c)
#define MAKE_OSP_STATUS(c)		MAKE_HRESULT(0, _FACOSP, c)

#define OSP_E_INVALID_SEGMENT     MAKE_OSP_HRESULT(1)
#define OSP_E_OPEN_URL            MAKE_OSP_HRESULT(2)
#define OSP_E_CREATE_FILTERGRAPH  MAKE_OSP_HRESULT(3)
#define OSP_E_HTTP_HANDLE         MAKE_OSP_HRESULT(4)
#define OSP_E_INVALID_URL         MAKE_OSP_HRESULT(5)
#define OSP_E_CANNOT_CONNECT      MAKE_OSP_HRESULT(6)
#define OSP_E_INVALID_RESPONSE    MAKE_OSP_HRESULT(7)
#define OSP_E_INVALID_DATA        MAKE_OSP_HRESULT(8)
#define OSP_E_NO_TRACK            MAKE_OSP_HRESULT(9)